/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        youtube: "#eb3223",
        instagram: "#eb3223",
        facebook: "#4968ad",
        twitch: "#644398",
        twitter: "#49a1eb",
        linkedin: "#3077b0",
        discord: "#f865f2",
        /* Semantic token-based colors */
        accent: "var(--color-accent)",
        accentHover: "var(--color-accent-hover)",
        "accent-subtle": "var(--color-accent-subtle)",
        text: "var(--color-text)",
        textMuted: "var(--color-text-muted)",
        "text-subtle": "var(--color-text-subtle)",
        bg: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-hover": "var(--color-surface-hover)",
        "section-elevated": "var(--color-section-elevated)",
        border: "var(--color-border)",
      },
      backgroundImage: {
        interviewing: "url('/images/overlays/interviewing.png')",
        talking: "url('/images/overlays/talking.png')",
        coding: "url('/images/overlays/coding.png')",
        waiting: "url('/images/overlays/waiting.png')",
      },
      fontFamily: {
        sans: [
          '"Inter Variable"',
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        display: [
          '"Space Grotesk Variable"',
          '"Space Grotesk"',
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        mono: ['"IBM Plex Mono"', '"SF Mono"', '"Fira Code"', "Consolas", "monospace"],
      },
      borderRadius: {
        none: "0",
        sm: "10px",
        DEFAULT: "12px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
        full: "9999px",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-card)",
        md: "var(--shadow-card)",
        lg: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
        none: "none",
      },
    },
  },
  safelist: [
    "text-youtube",
    "h-[0.5px]",
    "h-[2px]",
  ],
  plugins: [require("@tailwindcss/typography"), require("@tailwindcss/container-queries")],
};
